# fly.toml app configuration file generated for chathub-logshippper on 2024-03-04T21:20:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chathub-logshippper'
primary_region = 'sjc'

[build]
  image = 'ghcr.io/superfly/fly-log-shipper:latest'

[[services]]
  http_checks = []
  internal_port = 8686

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
